version: '3'
services:
  test-sharelyft:
    image: sharelyft:${BUILD_NUMBER}
    container_name: test-sharelyft
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgres://user:password@test-db:5432/sharelyft_test
    depends_on:
      - test-db
  
  test-db:
    image: postgres:14-alpine
    container_name: test-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sharelyft_test