version: '3'
services:
  test-sharelyft:
    image: sharelyft:${BUILD_NUMBER}
    container_name: test-sharelyft
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
    volumes:
      - ./members.db:/app/members.db